import db from "./realityDb.js";
import { EXTERNAL } from "./stats.js";
import { classify } from "./vendors/index.js";
import { AGENT_OWNER } from "./vendors/sources.js";
import { habits, agentOf } from "./patterns.js";

// Explanations for an observed habit — plural, always, and each with the
// observation that would tell it from the others.
//
// The failure this file is built against is a single hypothesis. "AI clients
// never reached /pricing, so the links to it may not be visible" reads as an
// explanation the moment it is the only one on the page, and the reader stops
// looking. The record supported four other readings equally well: nobody linked
// to it, the crawl never got that far, the page is new, or that crawler never
// came at all.
//
// So a habit yields a set, the set is never ranked by plausibility — that would
// be an opinion wearing a measurement's clothes — and every member carries the
// observation that would separate it. Where that observation is already in the
// record, it is run, and the candidate comes back supported or contradicted
// rather than merely stated. Where it is not, the candidate says what would have
// to be seen. That sentence is the experiment, written before anyone runs it.
//
// Nothing here is generated by a language model. Each rule is a fixed template
// over figures the pattern layer computed.

export const HYPOTHESIS_VERSION = "hyp-1";

// A path that describes the site rather than carrying its content. A crawler
// that reads only these has read the rules and the map, and has not read
// anything the site is about — which is a different fact from "it did not come".
const DESCRIPTIVE_PATHS = new Set(["/robots.txt", "/sitemap.xml", "/llms.txt", "/favicon.ico"]);

const vendorRequests = db.prepare(`
  SELECT userAgent, cfConnectingIp AS ip, path, observedAt, observedAtMs
  FROM RequestReality
  WHERE ${EXTERNAL} AND userAgent IS NOT NULL
  ORDER BY observedAtMs
`);

/** Corroborated requests, grouped by the company operating the crawler. */
function corroboratedByVendor() {
  const out = new Map();

  for (const r of vendorRequests.all()) {
    const agent = agentOf(r.userAgent);
    if (!agent) continue;

    const status = classify(agent, r.ip)?.status;
    if (status !== "verified" && status !== "vendor_other") continue;

    const vendor = AGENT_OWNER[agent];
    if (!out.has(vendor)) out.set(vendor, []);
    out.get(vendor).push({ ...r, agent });
  }

  return out;
}

/**
 * Candidate explanations for one crawler reading only descriptive paths.
 *
 * Every candidate names the observation that separates it. Three of them can be
 * checked against the record as it already stands, which is the point of writing
 * them this way — a hypothesis that could have been eliminated this morning and
 * was published as open is not a hypothesis, it is a gap in the reading.
 */
function forDescriptiveOnly(habit, vendorRows) {
  const agent = habit.agent;
  const vendor = habit.vendor;

  const siblings = vendorRows.filter((r) => r.agent !== agent);
  const siblingContent = siblings.filter((r) => !DESCRIPTIVE_PATHS.has(r.path));
  const ownContent = vendorRows.filter(
    (r) => r.agent === agent && !DESCRIPTIVE_PATHS.has(r.path)
  );

  // Our own rules, read back from the record of what this site actually served
  // rather than from the code that generates it. What matters is the bytes a
  // crawler received, and those are not always what the origin produced.
  const servedRobots =
    db
      .prepare(
        `SELECT body FROM SelfObservation
         WHERE path = '/robots.txt' AND vantage = 'edge' AND errorCode IS NULL
         ORDER BY observedAtMs DESC LIMIT 1`
      )
      .get()?.body ?? null;

  const weRefuseIt =
    servedRobots === null
      ? null
      : new RegExp(`user-agent:\\s*${agent}\\b[\\s\\S]{0,200}?disallow:\\s*/\\s*$`, "im").test(
          servedRobots
        );

  return [
    {
      id: "delegated",
      claim: `Reading the rules is delegated to ${agent}, and ${vendor} fetches content under a different identity.`,
      separatedBy: `a corroborated request from another ${vendor} crawler to a path that is not robots.txt, sitemap.xml or llms.txt`,
      status:
        siblings.length === 0
          ? "untested"
          : siblingContent.length > 0
            ? "supported"
            : "contradicted",
      evidence:
        siblings.length === 0
          ? `No other ${vendor} crawler has been corroborated here at all.`
          : siblingContent.length > 0
            ? `${siblingContent.length} such request${siblingContent.length === 1 ? "" : "s"} from ${[...new Set(siblingContent.map((r) => r.agent))].join(", ")}.`
            : `${siblings.length} corroborated request${siblings.length === 1 ? "" : "s"} from other ${vendor} crawlers, none of them to a content path.`
    },
    {
      id: "refused",
      claim: `This site's own rules, as delivered, tell ${agent} not to go further.`,
      separatedBy: `the robots.txt a client actually receives, read back from the edge`,
      status: weRefuseIt === null ? "untested" : weRefuseIt ? "supported" : "contradicted",
      evidence:
        weRefuseIt === null
          ? "The sensor has not yet recorded what the edge serves for this path."
          : weRefuseIt
            ? `The delivered robots.txt refuses ${agent}.`
            : `The delivered robots.txt does not refuse ${agent}. It names the AI crawlers it welcomes.`
    },
    {
      id: "not-yet",
      claim: `${vendor} has not reached this site's content yet, and would on a longer horizon.`,
      separatedBy: `time — a corroborated ${vendor} request to a content path on any later day`,
      status: ownContent.length > 0 ? "contradicted" : "untested",
      evidence:
        ownContent.length > 0
          ? `${agent} has already taken ${ownContent.length} content path${ownContent.length === 1 ? "" : "s"}.`
          : `Nothing in ${habit.days} day${habit.days === 1 ? "" : "s"} of observation settles this. Only a longer record can.`
    },
    {
      id: "by-design",
      claim: `Reading only descriptive files is what ${agent} is for, and no content fetch is expected from it at any horizon.`,
      separatedBy: `${vendor}'s own documentation of this crawler, which is a statement by the party being checked and is not evidence here`,
      status: "untested",
      evidence:
        "Deliberately left open. It would be settled by asking the vendor, and a vendor's account of its own crawler is exactly what this site declines to record as observation."
    }
  ];
}

/**
 * Every habit the pattern layer will describe, with its competing explanations.
 *
 * Only habits that passed the pattern layer's own threshold appear. A hypothesis
 * about a crawler seen twice is a hypothesis about nothing.
 */
export function hypotheses() {
  const byVendor = corroboratedByVendor();

  return habits()
    .filter((h) => h.describable)
    .flatMap((h) => {
      const sole = h.soleTargets[0];
      if (!sole || sole.share < 50) return [];
      if (!DESCRIPTIVE_PATHS.has(sole.path)) return [];

      const candidates = forDescriptiveOnly(h, byVendor.get(h.vendor) ?? []);

      return [
        {
          id: `${h.agent}-descriptive-only`,
          agent: h.agent,
          vendor: h.vendor,
          observation: `On ${sole.visits} of ${h.corroboratedVisits} corroborated visits, across ${h.days} days and ${h.addresses} addresses, ${h.agent} fetched ${sole.path} and nothing else.`,
          figures: {
            visits: h.corroboratedVisits,
            soleVisits: sole.visits,
            days: h.days,
            addresses: h.addresses,
            path: sole.path
          },
          candidates,
          // The count that decides whether this is worth reading. A set where
          // everything is untested has not used the record it was drawn from.
          settled: candidates.filter((c) => c.status !== "untested").length,
          open: candidates.filter((c) => c.status === "untested").length,
          version: HYPOTHESIS_VERSION
        }
      ];
    });
}
